import { Fragment } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';

import Main from 'components/Main';
import Deal from 'components/Deal/Deal';
import Carousel from 'components/Carousel/Carousel';
import { DealItemProps } from 'components/Deal/types';
import useAxios from 'hooks/useAxios';

import Mypage from 'components/Mypage';
import styled from '@emotion/styled';
import { CategoryListType, conCategory1s } from 'types';

interface HomeProps {
    conItems: DealItemProps[];
    mainCategory: conCategory1s[];
}

const Home: NextPage<HomeProps> = ({ conItems, mainCategory }) => {
    useAxios('/con-items/soon');

    return (
        <Fragment>
            <MainWrapper>
                <Head>
                    <title>NCNC App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Mypage />
                <Carousel />
                <Main conCategory1s={mainCategory} />
                <Deal onDealItems={conItems} />
            </MainWrapper>
        </Fragment>
    );
};

const MainWrapper = styled.div`
    background-color: #fff;
`;

export async function getStaticProps() {
    const fetchUrl = `https://api2.ncnc.app/con-items/soon`;
    const { data } = await axios.get<{ conItems: DealItemProps[] }>(fetchUrl);
    const conItems = data.conItems;

    const { data: category } = await axios.get<CategoryListType>(
        '/con-category1s',
    );
    const mainCategory = category.conCategory1s;

    return {
        props: { conItems, mainCategory },
    };
}
export default Home;
